#include <stdio.h>
#include <stdlib.h>
#include "ctype.h"

enum token_type{
TOKEN_IDENT = 1,
TOKEN_NUMERO_INT = 2,
TOKEN_NUMERO_REAL = 3, 
TOKEN_MENORQ = 4, //OPERADORES RELACIONAIS
TOKEN_MAIORQ = 5,
TOKEN_MENORQ_OU_IGUAL = 6,
TOKEN_MAIORQ_OU_IGUAL = 7,
TOKEN_IGUAL = 8,
TOKEN_DIFERENTE = 9, 
TOKEN_MAIS = 10, //OPERADORES ARITMETICOS
TOKEN_MENOS = 11,
TOKEN_MULT = 12,
TOKEN_DIV_REAIS = 13,
TOKEN_DIV_INTEIROS = 14, 
TOKEN_AND = 15,
TOKEN_OR = 16,
TOKEN_NOT = 17, 
TOKEN_ATRIBUICAO = 18, //OPERADOR DE ATRIBUICAO  
TOKEN_ABRE_PAR = 19, //SIMBOLOS ESPECIAIS
TOKEN_FECHA_PAR = 20,
TOKEN_VIRGULA = 21,
TOKEN_PONTO_E_VIRGULA = 22, 
TOKEN_PONTO = 23,
TOKEN_DOIS_PONTOS = 24,
TOKEN_PROGRAM = 25, //PALAVRAS RESERVADAS
TOKEN_IF = 26,
TOKEN_THEN = 27,
TOKEN_ELSE = 28,
TOKEN_WHILE = 29,
TOKEN_DO = 30,
TOKEN_REPEAT = 31,
TOKEN_UNTIL = 32,
TOKEN_INTEGER = 33,
TOKEN_REAL = 34,
TOKEN_CHAR = 35,
TOKEN_BEGIN = 36,
TOKEN_END = 37,
TOKEN_WRITE = 38,
TOKEN_VAR = 39,
TOKEN_DIV = 40,
};

struct token{
    enum token_type type;
    char lexeme[60];//escreve a palavra
};

int main(){
    printf("COMPILOU SEM ERROS\n");
    return 0;
}
